### ISSUE TITLE
UnhandledPromiseRejectionWarning on execute

### ISSUE THREAD

**Issue by sinklair** [kevnk/gulp-sendgrid#4]
Trying to use this and I get the following error on trying to upload a file

```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of undefined
    at [PATH]/node_modules/gulp-sendgrid/index.js:39:49
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:50137) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:50137) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by sinklair** [comment]
This appears to be an issue with referencing methods of Node.js path that are undefined in the function. Is there a missing require?
